---
functional:
- требование 1 Пользователь должен иметь возможность искать товары по ключевому слову или категории
- требование 2 Страница приложения должна иметь мобильную версию
- требование 3 Сайт должен открываться на различных устройствах
- требование 4 Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
- требование 5 Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
- требование 6 Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру 
non-functional:
 - требование 7 Кросс-браузернаясовместимость
 - требование 8 Сайт должен быть способен обрабатывать большое количество трафика
 - требование 9 Сайт должен быть протестирован на совместимость с последними версиями браузеров
 - требование 10 Сайт должен быть безопасным и защищать данные пользователя
implicit:
- требование 11 Сайт должен отражать информацию на английском и русском языке, при выборе каждого 
- требование 12 Понятность и привлекательность интерфейса
- требование 13 Пользователь должен иметь возможность менять количество товаров находясь в корзине
- требование 14 Невозможно оформить заказ с пустой корзиной
- требование 15 В списке производители, каждый производитель прописан единожды
- требование 16 В строке цена можно ввести только положительное значение и никакое другое
- требование 17 В строке поиск можно искать товар как на английском, так и на русском языке
- требование 18 Соблюдение единого стиля в отображении товаров в корзине
